import { StyleSheet } from "react-native";

/* Temporary
 */
export const styles = StyleSheet.create({
  safe: { flex: 1 },
  hintText: {},
  header: {},
  title: {},
  sub: {},
  subStrong: {},
  subMuted: {},
  smallBtn: {},
  smallBtnText: {},
  gridWrap: {},
  cell: {},
  cellFixed: {},
  cellSelected: {},
  cellConflict: {},
  cellText: {},
  cellTextFixed: {},
  actionsRow: {},
  actionBtn: {},
  actionText: {},
  keypad: {},
  keyBtn: {},
  eraseBtn: {},
  keyText: {},
  modalOverlay: {},
  modalCard: {},
  modalTitle: {},
  modalSub: {},
  input: {},
  modalRow: {},
  modalBtn: {},
  modalBtnGhost: {},
  modalBtnText: {},
  lbRow: {},
  lbRank: {},
  lbName: {},
  lbMeta: {},
  lbTime: {},
});
