import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    alignItems: "center",
    paddingTop: 12,
    paddingHorizontal: 12,
    backgroundColor: "#0b0f14",
  },
  header: {
    width: "100%",
    maxWidth: 520,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 10,
  },
  title: { color: "#fff", fontSize: 28, fontWeight: "800" },
  sub: { color: "#cbd5e1", marginTop: 2 },
  subStrong: { color: "#fff", fontWeight: "900" },
  subMuted: { color: "#94a3b8" },
  smallBtn: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#374151",
  },
  smallBtnText: { color: "#e5e7eb", fontWeight: "900" },

  gridWrap: { backgroundColor: "#111827", borderRadius: 12, padding: 6 },
  cell: {
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#374151",
    backgroundColor: "#0f172a",
  },
  cellFixed: { backgroundColor: "#111827" },
  cellSelected: { backgroundColor: "#1f2937" },
  cellConflict: { backgroundColor: "#7f1d1d" },
  cellText: { color: "#e5e7eb", fontSize: 18, fontWeight: "700" },
  cellTextFixed: { color: "#93c5fd", fontWeight: "900" },

  actionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
    marginBottom: 10,
    justifyContent: "center",
  },
  actionBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#374151",
  },
  actionText: { color: "#e5e7eb", fontWeight: "900" },

  keypad: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: Math.min(Dimensions.get("window").width - 24, 420),
    gap: 10,
    justifyContent: "center",
    marginTop: 6,
  },
  keyBtn: {
    width: "30%",
    minWidth: 90,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#374151",
    alignItems: "center",
  },
  eraseBtn: { width: "95%" },
  keyText: { color: "#fff", fontSize: 18, fontWeight: "900" },

  hintText: {
    marginTop: 10,
    color: "#9ca3af",
    textAlign: "center",
    maxWidth: 520,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    width: "100%",
    maxWidth: 520,
    backgroundColor: "#0f172a",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#334155",
    padding: 16,
  },
  modalTitle: { color: "#fff", fontSize: 20, fontWeight: "900" },
  modalSub: { color: "#94a3b8", marginTop: 6 },
  input: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#334155",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#fff",
    backgroundColor: "#111827",
    fontWeight: "800",
  },
  modalRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
    justifyContent: "flex-end",
  },
  modalBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#475569",
  },
  modalBtnGhost: { backgroundColor: "transparent", borderColor: "#334155" },
  modalBtnText: { color: "#e5e7eb", fontWeight: "900" },

  lbRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#334155",
  },
  lbRank: { color: "#93c5fd", fontWeight: "900", width: 46 },
  lbName: { color: "#fff", fontWeight: "900", fontSize: 16 },
  lbMeta: { color: "#94a3b8", marginTop: 2, fontSize: 12 },
  lbTime: { color: "#fff", fontWeight: "900", fontSize: 16 },
});
